version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=hdariodev
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - /postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
